### ISSUE TITLE
Ask for the paper

### ISSUE THREAD

**Issue by XPwastaken** [HaoliangZhou/IncepTR#1]
您好！ 我对您的项目非常感兴趣，我很想进一步了解这份源码，想参考一下论文，可是我没有搜索到这篇文章。请问您可以把论文发给我一份吗？
我的邮箱是 z1985690318@gmail.com
十分感谢！

**Comment by HaoliangZhou** [comment]
你好，因paper还在审稿中，可能还有部分问题，暂无法发布

**Comment by HaoliangZhou** [comment]
> 
你好 你可以在这里下载https://link.springer.com/article/10.1007/s00530-023-01164-0
