### ISSUE TITLE
Dataset问题，与训练文件中的transform问题

### ISSUE THREAD

**Issue by 1938254962** [HaoliangZhou/IncepTR#3]
尊敬的作者您好，我最近在尝试运行您的代码，但是我在学习代码的时候发现一些问题：
1、您的Dataset中对输入的数据是采用的np.load()，加载的是.npz文件，这与您Dual-ATME中的输入方式不同，我想问是不是因为您在将光流的u，v，以及应变分量，以通道融合时保存成RGB图像出现了问题（保存的图像是全黑的），从而您使用了npz的文件进行输入？
2、您在使用np.savez()操作时，是否使用的类似于这段代码：np.savez(path , of = img)
3、在训练代码中，有对输入图像进行Resize等操作的代码，但是在用到Dataset时却没有进行transform操作，而是只对输入图像进行如下操作，这与我之前看到的代码有所不同，所以想向您询问这个是为什么呢？
of = torch.FloatTensor(img['of'])
of = of.permute(2, 0, 1)

学生不才，非常期待得到您在百忙之中的答复，感谢

**Comment by HaoliangZhou** [comment]
你好，关于你提到的问题：
1. 是的inceptr和dual-atme的输入不同，后者是直接载入合成后的uve的png图片，而inceptr是把这些数据写到了npz文件，但你仍然可以改成直接读取image的方式，这并不影响。我改成npz是后面换了一种矫正方式和数据保存方式，并不是保存的图像是全黑哈。
2. 是的，但是我保存成npz的代码好像没找到，所以只能你再去找找了（如果也想要用.npz作为输入）
3. 感谢指出问题！使用npz的情况下，main函数那里可以直接删掉data transform，这是因为直接读取png之类的image才需要做各自transform；然而我后面采用直接读取npz，每个npz文件都已经是比如28*28的矩)了（已经是tensor了，不再是从图像开始），所以就没用到data transform了。
你可以follow整个过程包括制作npz文件；可以只用模型而保持读取图像的那种范式。
还有其他问题欢迎咨询~

**Comment by 1938254962** [comment]
非常感谢您及时的回复，还有两个问题就是：
1、您训练一次代码的时间大概为多长时间？
2、就是我在训练代码中看到您通过for循环，循环训练了10次模型，这是为什么？

**Comment by 1938254962** [comment]
非常感谢您及时的回复，还有几个问题就是：
1、您训练一次代码的时间大概为多长时间？
2、就是我在训练代码中看到您通过for循环，循环训练了10次模型，这是为什么？

**Comment by 1938254962** [comment]
非常感谢您及时的回复，还有几个问题就是：
1、我在运行Dual-ATME的代码时，代码时可以跑的，但是在使用以下代码进行保存结果时出现了转换错误，不知道您换成npz的输入方式是不是在规避这个错误呢？    
运行代码：
allRST = np.array(allRST)
rstPath = os.path.join('result', model_name + '_lr' + str(lr) + '_rst.mat')
scio.savemat(rstPath, {'Xia': allRST})

出现的错误：
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (68, 2) + inhomogeneous part.

2、您训练一次代码的时间大概为多长时间？
3、就是我在训练代码中看到您通过for循环，循环训练了10次模型，这是为什么？

**Comment by HaoliangZhou** [comment]
你好，关于上述问题：
1.我转换维npz单纯就是改了下输入的情况，没有因为其他原因，然后在dual-atme中也是可以正常保存的。你如果这个无法保存你可以试试直接保存成各种文件形式，总之这个文件就是一列真实标签，一列预测值就行，方便后面对实验结果的分析和计算
2.dual-atme久点 因为是图像，3090/4090上大概2小时？有点忘了，后面inceptr因为输入是npz就比较快，应该是一小时不到
3.这就是epoch，训练10个epoch然后进行测试

**Comment by 1938254962** [comment]
好的，非常感谢您的回答！

**Comment by shialongya** [comment]
> 尊敬的作者您好，我最近在尝试运行您的代码，但是我在学习代码的时候发现一些问题： 1、您的数据集中对输入的数据是采用的np.load（），加载的是.npz文件，这与您Dual-ATME中的输入方式不同，我想问是不是因为您在将光流的u，v，以及应变分量，以通道融合时保存成RGB图像出现了问题（保存的图像是全黑的），从而您使用了npz的文件进行输入？ 2、您在使用np.savez（）操作时，是否使用的类似于这段代码：np.savez（path ， of = img） 3、在训练代码中，有对输入图像进行Resize等操作的代码，但是在用到Dataset时却没有进行转换操作，而是只对输入图像进行如下操作，这与我之前看到的代码有所不同，所以想向您询问这个是为什么呢？ 的 = 火炬。FloatTensor（img['of']） of = of.permute（2， 0， 1）
> 
> 学生不才，非常期待得到您在百忙之中的答复，感谢
你好，想请教您一下，我在尝试跑代码过程放入整理好的v_cde_flow和光流图运行过程中中出现ValueError: invalid literal for int() with base 10:报错是什么原因的，希望能得到您的回复
![image](https://github.com/HaoliangZhou/IncepTR/assets/110446192/b4446def-5fcb-469d-baca-a3e3f8ae0f86)

**Comment by shialongya** [comment]
> 尊敬的作者您好，我最近在尝试运行您的代码，但是我在学习代码的时候发现一些问题： 1、您的Dataset中对输入的数据是采用的np.load()，加载的是.npz文件，这与您Dual-ATME中的输入方式不同，我想问是不是因为您在将光流的u，v，以及应变分量，以通道融合时保存成RGB图像出现了问题（保存的图像是全黑的），从而您使用了npz的文件进行输入？ 2、您在使用np.savez()操作时，是否使用的类似于这段代码：np.savez(path , of = img) 3、在训练代码中，有对输入图像进行Resize等操作的代码，但是在用到Dataset时却没有进行transform操作，而是只对输入图像进行如下操作，这与我之前看到的代码有所不同，所以想向您询问这个是为什么呢？ of = torch.FloatTensor(img['of']) of = of.permute(2, 0, 1)
> 
> 学生不才，非常期待得到您在百忙之中的答复，感谢

您好，可以加下您的联系vx么想向您请教些问题

**Comment by HaoliangZhou** [comment]
614136484发自我的手机-------- 原始邮件 --------发件人： shialong ***@***.***>日期： 2024年1月6日周六 傍晚5:43收件人： HaoliangZhou/IncepTR ***@***.***>抄送： HaoliangZhou ***@***.***>, Comment ***@***.***>主    题： Re: [HaoliangZhou/IncepTR] Dataset问题，与训练文件中的transform问题 (Issue #3)

尊敬的作者您好，我最近在尝试运行您的代码，但是我在学习代码的时候发现一些问题： 1、您的Dataset中对输入的数据是采用的np.load()，加载的是.npz文件，这与您Dual-ATME中的输入方式不同，我想问是不是因为您在将光流的u，v，以及应变分量，以通道融合时保存成RGB图像出现了问题（保存的图像是全黑的），从而您使用了npz的文件进行输入？ 2、您在使用np.savez()操作时，是否使用的类似于这段代码：np.savez(path , of = img) 3、在训练代码中，有对输入图像进行Resize等操作的代码，但是在用到Dataset时却没有进行transform操作，而是只对输入图像进行如下操作，这与我之前看到的代码有所不同，所以想向您询问这个是为什么呢？ of = torch.FloatTensor(img['of']) of = of.permute(2, 0, 1)
学生不才，非常期待得到您在百忙之中的答复，感谢

您好，可以加下您的联系vx么想向您请教些问题

**Comment by HaoliangZhou** [comment]
> > 尊敬的作者您好，我最近在尝试运行您的代码，但是我在学习代码的时候发现一些问题： 1、您的Dataset中对输入的数据是采用的np.load()，加载的是.npz文件，这与您Dual-ATME中的输入方式不同，我想问是不是因为您在将光流的u，v，以及应变分量，以通道融合时保存成RGB图像出现了问题（保存的图像是全黑的），从而您使用了npz的文件进行输入？ 2、您在使用np.savez()操作时，是否使用的类似于这段代码：np.savez(path , of = img) 3、在训练代码中，有对输入图像进行Resize等操作的代码，但是在用到Dataset时却没有进行transform操作，而是只对输入图像进行如下操作，这与我之前看到的代码有所不同，所以想向您询问这个是为什么呢？ of = torch.FloatTensor(img['of']) of = of.permute(2, 0, 1)
> > 学生不才，非常期待得到您在百忙之中的答复，感谢
> 
> 您好，可以加下您的联系vx么想向您请教些问题

614136484
