### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by shialongya** [HaoliangZhou/IncepTR#4]
想请问一下一般出现这个报错是什么原因
![image](https://github.com/HaoliangZhou/IncepTR/assets/110446192/159f5eb4-b6a1-4d4e-8ce8-f2bd7701c289)

**Comment by HaoliangZhou** [comment]
你好，你把数据做成了npz格式了吗，这个错误我没遇到过，应该是加载内容相关的错误。你可以试着搜索一下google

**Comment by shialongya** [comment]
> 你好，你把数据做成了npz格式了吗，这个错误我没遇到过，应该是加载内容相关的错误。你可以试着搜索一下google

你好感谢您在百忙之中回复我
我是按照readme中放的数据集
![image](https://github.com/HaoliangZhou/IncepTR/assets/110446192/f6fff2da-d75a-4598-84a1-2824dadaa046)
这个问题困扰了我几天，并没有做成npz格式

不过放到DUAL-ATME可以跑通不知道是什么原因

**Comment by shialongya** [comment]
![image](https://github.com/HaoliangZhou/IncepTR/assets/110446192/9793e43c-9a41-446e-b42c-8fffe874d118)
是需要修改这里的哪个部分吗

**Comment by shialongya** [comment]
> 你好，你把数据做成了npz格式了吗，这个错误我没遇到过，应该是加载内容相关的错误。你可以试着搜索一下google

恳请能得到您的建议

**Comment by HaoliangZhou** [comment]
因为Inceptr读取的是npz，不是png，所以在def __getietm__中，你需要把我原来读取npz格式的52-55行代码，改成读取png的流程

**Comment by shialongya** [comment]
> 因为Inceptr读取的是npz，不是png，所以在def __getietm__中，你需要把我原来读取npz格式的52-55行代码，改成读取png的流程

十分感谢
